name: screen_time_tracker
description: A Flutter package to track and monitor the time spent on different screens in your app.
version: 1.0.0
homepage: https://github.com/AgnivaMaiti/screen_time_tracker
repository: https://github.com/AgnivaMaiti/screen_time_tracker
license: MIT

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.example.screen_time_tracker
        pluginClass: ScreenTimeTrackerPlugin
      ios:
        pluginClass: ScreenTimeTrackerPlugin
